### ISSUE TITLE
Upcoming breaking changes

### ISSUE THREAD

**Issue by blake-mealey** [blake-mealey/mantle#119]
A list of upcoming breaking changes I am considering (hopefully we can group all of these into one major version bump):

* ~Rename `environment.name` to `environment.label`~
  * ~Related: rename place, product, badge, etc. "names" to "labels" throughout the docs (this is non-breaking)~
* ~Rename `environment.overrides` to `environment.targetOverrides`~
* ~Refactor `experience.configuration.paidAccessPrice` to use a more consistent style:~
```yml
# Enabled with a price
paidAccess:
  price: 50
# Disabled (default)
paidAccess: disabled
```
* ~Refactor `experience.configuration.privateServerPrice` to use a more consistent style:~
```yml
# Enabled with a price
privateServers:
  price: 50
# Enabled for free
privateServers: free
# Disabled (default)
privateServers: disabled
```
* ~Refactor `state.remote.region` to use a more consistent style:~
```yml
# Stndard region
region: us-west-2
# Custom region
region:
  custom:
    name: string
    endpoint: url
```
* Refactor `experience.passes.*.price` to use a more consistent style: (?)
  * Not sure about this one, leaving it for now
```yml
# For sale, with a price
sale:
  price: 20
# Free
sale: free
# Not for sale
sale: disabled
```
* ~Move `experience.configuration.icon` and `experience.configuration.thumbnails` up a level~
