### ISSUE TITLE
Can't upload secondary place

### ISSUE THREAD

**Issue by MayGo** [blake-mealey/mantle#219]
In mantle.yml I have 2 places:
```
   places:
      start:
        file: GameLobby.rbxlx
        configuration:
          name: Monsters Nearby
          description: A game!
          maxPlayerCount: 20

      waiting:
        file: GameWaitingLobby.rbxlx
        configuration:
          name: Monsters Nearby Waiting Lobby
```
When running `mantle deploy --environment development`

I get error 
Failed: Roblox error (404 Not Found): 404 | Page Not found

I think it is because Roblox deprecated http://data.roblox.com/Data/Upload.ashx
Used in [
](https://github.com/blake-mealey/mantle/blob/main/mantle/rbx_api/src/places/mod.rs#L49)

Blog post: https://devforum.roblox.com/t/official-list-of-deprecated-web-endpoints/62889/62

NB! This is an awesome project!
