### ISSUE TITLE
Can't override existing passes?

### ISSUE THREAD

**Issue by Etheroit** [blake-mealey/mantle#223]
**Describe the bug**
I've been trying to override the settings of a pass but either I am doing something wrong or something isn't working correctly but I'd suspect the second as the config seems to be compliant with the api reference.

Everything works properly if `environments[0].targetOverrides.passes` is removed from the below config.

My shortened config:
```
...
environments:
  - label: dev
    targetNamePrefix: environmentLabel
    targetOverrides:
      places:
        start:
          configuration:
            description: |-
              (the new description here)
      passes:
        testPass:
          name: '(other name here)'
          description: '(other description here)'
          price: 1
...

target:
  experience:
...(other config here including but not limited to the places)
    passes:
      testPass:
        name: (name here)
        description: (description here)
        icon: assets/tools/testimage.png
...
```

**Expected behavior**
I would expect the targetOverrides to change the 'testPass' name, description and also set price to 1 in certain environment. Instead I am seeing an error:
```
Unable to parse config file ./mantle.yml
	environments[0]: data did not match any variant of untagged enum TargetOverridesConfig at line 9 column 10
```
