### ISSUE TITLE
add a mantle preview command to create a preview deployment

### ISSUE THREAD

**Issue by blake-mealey** [blake-mealey/mantle#41]
use case: create a preview deployment from all PRs

dependent on #40 for post-merge cleanup
also dependent on #21 for making previews private access

**Comment by blake-mealey** [comment]
Running `mantle preview create` will:

1. Create a new temporary environment (not saved back to config file) with the configuration:

```yml
name: preview-<branch-name>-<pr-number> # is this sufficiently unique/understandable?
overrides:
  places:
    *:
      configuration:
        name: Preview (<pr-number>): <name>
```

2. Deploy to the temporary environment
3. Add the temporary environment to the state file

Running `mantle preview destroy` will:

1. Look for a temporary environment in the state file with the name format described above
2. Destroy the environment if it exists
3. Remove the temporary environment from the state file
