### ISSUE TITLE
restructure config API to support future non-experience deployments (e.g. models or plugins)

### ISSUE THREAD

**Issue by blake-mealey** [blake-mealey/mantle#43]

**Comment by blake-mealey** [comment]
I think we can actually add this without any restructuring just by making experience and places optional.

**Comment by blake-mealey** [comment]
After some further thought, I am considering the following config API:

```yml
# target an experience
target:
  experience:
    configuration:
      genre: naval
    places:
      start:
        file: place.rbxlx
        configuration:
          name: Start place
    products:
    passes:
    badges:
    assets:
```

```yml
# target a plugin
target:
  plugin:
    file: plugin.rbxmx
    configuration:
      name: My plugin
```

```yml
# target a model
target:
  model:
    file: model.rbxmx
    configuration:
      name: My model
```

**Comment by blake-mealey** [comment]
We could also consider supporting multiple targets with a slightly modified API:

```yml
targets:
  - plugin: {}
  - experience: {}
  - model: {}
  - model: {}
```
