### ISSUE TITLE
support group-owned experiences

### ISSUE THREAD

**Issue by blake-mealey** [blake-mealey/mantle#58]
Currently we only support personal experiences. In the future if we can use only Open Cloud APIs we may not need to specifically specify a group ID since API tokens will be created for the group, but for now we will need to specify a group ID to most endpoints to specify where resources should be created.

Potential configuration API:

```yml
# default:
owner: personal

# group:
owner:
  group: <id>
```
