### ISSUE TITLE
consider renaming deployments config field to environments

### ISSUE THREAD

**Issue by blake-mealey** [blake-mealey/mantle#64]
I think the term "environments" makes more sense for what the `deployments` field defines.

**Comment by blake-mealey** [comment]
Proposed configuration API:

```yml
environments:
  - name: staging
    branches: [dev, dev/*]
    overrides: { }
  - name: production
    branches: [main]
    tagCommit: true
    overrides: { }
```
