### ISSUE TITLE
support experience social links

### ISSUE THREAD

**Issue by blake-mealey** [blake-mealey/mantle#71]
Propose config API:

```yml
templates:
  experience:
    socialLinks:
      - title: Discord Server
        url: https://discord.gg/code
```

Determine "type" based on URL domain name.
