### ISSUE TITLE
add automated tests

### ISSUE THREAD

**Issue by blake-mealey** [blake-mealey/mantle#84]
I really should have done this from the start... 😐

I'm thinking unit tests + integration tests are probably a good idea.

**Comment by blake-mealey** [comment]
Adding to milestone v1.0.0 because this is definitely not production-ready until it is properly tested.

**Comment by blake-mealey** [comment]
I definitely should add some unit tests but atm I'm more interested in integration tests because I think they are more likely to uncover bugs that may have been caused by Roblox API changes (e.g. https://github.com/blake-mealey/mantle/issues/110) or just because some features haven't been tested as often during development but only break when actually hitting Roblox's APIs (e.g. https://github.com/blake-mealey/mantle/issues/97).

In order to uncover issues related to Roblox API changes, it would be ideal to run the tests frequently even when not under active development, so I would like to setup a nightly (or even weekly?) test run.

It would be nice to setup integration tests in a declarative format for example as a series of YAML documents:

```yml
config:
  environments:
    - label: staging
  target:
    experience:
      places:
        start:
          file: place.rbxlx
files:
  place.rbxlx: create
command: deploy -e staging
---
files:
  place.rbxlx: update
command: deploy -e staging
---
config:
  environments:
    - label: staging
  target:
    experience:
      places:
        start:
          file: place.rbxlx
      assets:
        - assets/*
files:
  assets/texture.png: create
command: deploy -e staging
---
command: destroy -e staging
```

By default the executor could assume to expect a successful command, but if it is expected to fail, the test could include something like:

```yml
expect:
  error: 404 Not Found
```
